name: "Verify version consistency"
description: "Verify that version in info.json matches the expected version"
author: "sakuro"
inputs:
  expected_version:
    description: "Expected version to match"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        FILE_VERSION="$(jq -r '.version' info.json)"
        if [ "$FILE_VERSION" != "${{ inputs.expected_version }}" ]; then
          echo "❌ Error: Version mismatch. File: $FILE_VERSION, Expected: ${{ inputs.expected_version }}"
          exit 1
        fi
        echo "✅ Version consistency verified: $FILE_VERSION"
